language: java
jdk:
- oraclejdk8
notifications:
  hipchat:
    rooms:
      secure: GfnIbeGH+EmWCra+WMOZNsF+o2tmbsvZir7Wowc6tNwYVRX3mO6ZN4b+Y7UPLBQ9QnissMatW3CjwvcHaQBUj5PmDF7HTShoW7PBYISRz21cm0NDVEJhsHPzBWFU/74Bs7bOeT4qZ1joVGvE1u25RizQQFnr48Glcdz9r3rx6QoX/EaWC/x9YGHxZIzkQ94PJuo3bjC6A5qw328src6+cBFyFz2BqEHFtkoe8WTHGg2bXVbZKRc20IALO7xydNN+C8g0Jc0PpUD++oFQBcm/nw0DYHt4hWnFW9q04R7jClDbtNuDtpJTP1lHcSrEDBDUlLv8gEkX4qRO0Dx1yjPPBbWk37xmuo4Mv5JHoHkOWQqCueYkKRMmyryF2iS8q1OG/tVhCnnujVMfBkm/w95Qs/kaFD+cGFhJuwETSUqCvL194tL5Y4JgF9q+XAUGZY6sgBWQCKTulA+nhnGFWDDsShuYt9HAYyJLJnn/HpHVi4j9bjg2VWERNl+luye0fSEkxk2F7MeUgHTf8logaS6yXQoxJedxH+nSVq5cA4EDHBItgJa/LCNZ6O2EhJkbOZEfyalGPLOeyL5AJwkvo55FFzbrbgr+JFfSb76enzDpy1BNxjfG71ok78BEMh43MLjPQ6oh1wJ92/TTcBnnfo6eFP1Y8joc92Mxyk2+N3xUh2k=
